### ISSUE TITLE
Good name for the repo

### ISSUE THREAD

**Issue by Bhargav-Rao** [SOBotics/Natty_plots#1]
We need a good name for the repo, @Ax3man has suggested "Bot_diagnostics". 

Do come up with others.

**Comment by ArcticEcho** [comment]
Perhaps Plotty?

**Comment by BaumMitAugen** [comment]
SOPlotics

**Comment by Floern** [comment]
[Shape](https://en.wikipedia.org/wiki/Supreme_Headquarters_Allied_Powers_Europe)

**Comment by Floern** [comment]
Plottwist

**Comment by BasicNullification** [comment]
StatSO

...or 

StatSOBot : 

> _Statistics for SO Bots_
